# Generated by Django 5.0.6 on 2024-12-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelField',
            fields=[
                ('roll', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('file_field', models.FileField(upload_to='./first_app/upload/')),
                ('url_field', models.URLField()),
                ('date_field', models.DateField()),
            ],
        ),
    ]
