# Generated by Django 5.0.6 on 2024-12-20 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=255, primary_key=True, serialize=False)),
                ('instrument_type', models.CharField(choices=[('guitar', 'Guitar'), ('ukulele', 'Ukulele'), ('cajon', 'Cajon'), ('flute', 'Flute'), ('violin', 'Violin'), ('piano', 'Piano')], max_length=50)),
            ],
        ),
    ]
