# Generated by Django 5.0.6 on 2024-12-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=50)),
                ('task_description', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('task_assign_date', models.DateField()),
            ],
        ),
    ]
